# Generated by Django 5.1.2 on 2024-10-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_eventregistration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'phone_number')},
        ),
    ]
