# Generated by Django 5.1.2 on 2024-10-28 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_eventregistration_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'email')},
        ),
    ]
