# Generated by Django 5.1.2 on 2024-11-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_eventregistration_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
