# Generated by Django 5.1.3 on 2024-11-25 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('about', models.TextField(max_length=450)),
                ('image', models.ImageField(upload_to='artists/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120)),
                ('answer', models.TextField(max_length=350)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='reels/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('updated_at', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=120)),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_url', models.URLField(blank=True, max_length=220, null=True, unique=True)),
                ('ig_url', models.URLField(blank=True, max_length=220, null=True, unique=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=220, null=True, unique=True)),
                ('x_url', models.URLField(blank=True, max_length=220, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='testimonies/')),
                ('message', models.TextField(max_length=350)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('updated_at', 'created_at'), 'verbose_name_plural': 'Galleries'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pastor',
            name='fb_url',
        ),
        migrations.RemoveField(
            model_name='pastor',
            name='ig_url',
        ),
        migrations.RemoveField(
            model_name='pastor',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='pastor',
            name='x_url',
        ),
        migrations.AddField(
            model_name='event',
            name='map',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='overview',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_gallery', to='app.event')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_gallery', to='app.gallery')),
            ],
            options={
                'verbose_name_plural': 'Event Galleries',
                'ordering': ('is_active', 'event', 'gallery'),
            },
        ),
        migrations.CreateModel(
            name='EventFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_faq', to='app.event')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_faq', to='app.faq')),
            ],
        ),
        migrations.CreateModel(
            name='EventPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_partner', to='app.event')),
                ('patner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_partner', to='app.partner')),
            ],
        ),
        migrations.CreateModel(
            name='EventReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reel', to='app.event')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reel', to='app.reel')),
            ],
            options={
                'verbose_name_plural': 'Event Reels',
                'ordering': ('is_active', 'event', 'reel'),
            },
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_schedule', to='app.event')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_schedule', to='app.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_social_link', to='app.artist')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_social_link', to='app.sociallink')),
            ],
        ),
        migrations.CreateModel(
            name='EventTestimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_testimony', to='app.event')),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_testimony', to='app.testimony')),
            ],
        ),
        migrations.CreateModel(
            name='UserSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_social_link', to='app.sociallink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_social_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
