# Generated by Django 5.1.3 on 2024-11-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastor',
            options={'ordering': ('position', 'created_at')},
        ),
        migrations.RemoveField(
            model_name='pastor',
            name='is_active',
        ),
    ]
