# Generated by Django 5.1.3 on 2024-11-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cellgroup',
            options={'ordering': ('is_active', 'created_at'), 'verbose_name_plural': 'Cell Groups'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'verbose_name_plural': 'Event Registrations'},
        ),
        migrations.AddField(
            model_name='event',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
