# Generated by Django 5.1.3 on 2024-11-12 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pastor_options_remove_pastor_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('is_active', 'created_at'), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('is_active', 'created_at'), 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='ministry',
            options={'ordering': ('is_active', 'created_at'), 'verbose_name_plural': 'Ministries'},
        ),
        migrations.AddField(
            model_name='pastor',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pastor/'),
            preserve_default=False,
        ),
    ]
