# Generated by Django 5.1.3 on 2024-11-26 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_artist_faq_partner_reel_schedule_sociallink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-start_at']},
        ),
        migrations.AlterField(
            model_name='artistsociallink',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='app.artist'),
        ),
        migrations.AlterField(
            model_name='artistsociallink',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_link', to='app.sociallink'),
        ),
        migrations.AlterField(
            model_name='event',
            name='map',
            field=models.URLField(max_length=550),
        ),
        migrations.AlterField(
            model_name='eventfaq',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='app.event'),
        ),
        migrations.AlterField(
            model_name='eventfaq',
            name='faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='app.faq'),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='app.event'),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='app.gallery'),
        ),
        migrations.AlterField(
            model_name='eventpartner',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='app.event'),
        ),
        migrations.AlterField(
            model_name='eventpartner',
            name='patner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='app.partner'),
        ),
        migrations.AlterField(
            model_name='eventreel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='app.event'),
        ),
        migrations.AlterField(
            model_name='eventreel',
            name='reel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='app.reel'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.event'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.schedule'),
        ),
        migrations.AlterField(
            model_name='eventtestimony',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='app.event'),
        ),
        migrations.AlterField(
            model_name='eventtestimony',
            name='testimony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='app.testimony'),
        ),
        migrations.AlterField(
            model_name='usersociallink',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='app.sociallink'),
        ),
        migrations.AlterField(
            model_name='usersociallink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
